### ISSUE TITLE
[FEAT] 장행빛의 Issue

### ISSUE THREAD

**Issue by biiit4894** [Likelion-at-SMWU-10th/git_test#5]
## 🫶 Todo
- [ ] 과제 제출방법 복습
- [ ] conflict 해결하는 법 실습
- [ ] 해커톤때 쓸 레포 세팅
